// Command gencontract synchronizes the C shim contract identifier with Go.
//
// The identifier changes whenever the shim implementation or public header
// changes. A binary built from an older checkout is therefore rejected before
// any shim entry point is exposed.
package main

import (
	"bytes"
	"crypto/sha256"
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
)

func main() {
	check := flag.Bool("check", false, "fail when generated files are stale")
	printID := flag.Bool("print", false, "print the current contract identifier")
	flag.Parse()

	root, err := moduleRoot()
	if err != nil {
		fatal(err)
	}
	id, err := contractID(root)
	if err != nil {
		fatal(err)
	}
	if *printID {
		fmt.Printf("0x%016x\n", id)
		return
	}

	files := map[string][]byte{
		filepath.Join(root, "internal", "shim", "contract_generated.go"): goOutput(id),
		filepath.Join(root, "shim", "ffshim_contract.h"):                 cOutput(id),
	}
	for path, want := range files {
		got, err := os.ReadFile(path)
		if *check {
			if err != nil || !bytes.Equal(got, want) {
				fatal(fmt.Errorf("generated shim contract is stale: run go generate ./internal/shim (%s)", filepath.ToSlash(path)))
			}
			continue
		}
		if err == nil && bytes.Equal(got, want) {
			continue
		}
		if err := os.WriteFile(path, want, 0o644); err != nil {
			fatal(fmt.Errorf("write %s: %w", path, err))
		}
	}
}

func moduleRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", errors.New("go.mod not found from current directory")
		}
		dir = parent
	}
}

func contractID(root string) (uint64, error) {
	hash := sha256.New()
	for _, name := range []string{"shim/ffshim.c", "shim/ffshim.h", "internal/shim/shim.go"} {
		contents, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(name)))
		if err != nil {
			return 0, fmt.Errorf("read %s: %w", name, err)
		}
		_, _ = fmt.Fprintf(hash, "%s\x00", name)
		_, _ = hash.Write(contents)
		_, _ = hash.Write([]byte{0})
	}
	sum := hash.Sum(nil)
	return uint64(sum[0])<<56 | uint64(sum[1])<<48 | uint64(sum[2])<<40 | uint64(sum[3])<<32 |
		uint64(sum[4])<<24 | uint64(sum[5])<<16 | uint64(sum[6])<<8 | uint64(sum[7]), nil
}

func goOutput(id uint64) []byte {
	return []byte(fmt.Sprintf("// Code generated by internal/shim/cmd/gencontract; DO NOT EDIT.\n\npackage shim\n\nconst ContractID uint64 = 0x%016x\n", id))
}

func cOutput(id uint64) []byte {
	return []byte(fmt.Sprintf("/* Code generated by internal/shim/cmd/gencontract; DO NOT EDIT. */\n#ifndef FFSHIM_CONTRACT_H\n#define FFSHIM_CONTRACT_H\n\n#include <stdint.h>\n\n#define FFSHIM_CONTRACT_ID UINT64_C(0x%016x)\n\n#endif\n", id))
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "gencontract:", err)
	os.Exit(1)
}
