/* Code generated by internal/shim/cmd/gencontract; DO NOT EDIT. */
#ifndef FFSHIM_CONTRACT_H
#define FFSHIM_CONTRACT_H

#include <stdint.h>

#define FFSHIM_CONTRACT_ID UINT64_C(0x8e5cebc067810f21)

#endif
